on: push

jobs:

  build-and-upload:
    name: build and upload
    strategy:
      matrix:
        os: [macos, ubuntu]
        include:
          - os: ubuntu
            runs: ubuntu-latest
            artifact-name: sup-linux-amd64
          - os: macos
            runs: macos-latest
            artifact-name: sup-macos-amd64
    runs-on: ${{ matrix.runs }}

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: coursier/cache-action@v6

      - name: compile for ${{ matrix.os }}
        run: |
          ./sbt compile

      - uses: graalvm/setup-graalvm@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}


      - name: build for ${{ matrix.os }}
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          ./sbt graalvm-native-image:packageBin

      # disable on window: https://github.com/upx/upx/issues/559
      - name: run upx on ${{ matrix.os }}
        uses: svenstaro/upx-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          file: target/graalvm-native-image/scala-interactive-update
          args: --best --lzma

      - name: upload ${{ matrix.os }}
        uses: actions/upload-artifact@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          name: ${{ matrix.artifact-name }}
          path: target/graalvm-native-image/scala-interactive-update

      - name: release binaries
        uses: svenstaro/upload-release-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/graalvm-native-image/scala-interactive-update
          asset_name: ${{ matrix.artifact-name }}
          overwrite: true
          tag: ${{ github.ref }}

      - name: Update Homebrew Formula
        uses: izumin5210/action-homebrew-tap@releases/v0
        if: startsWith(github.ref, 'refs/tags)/')
        with:
          tap: kitlangton/homebrew-scala-interactive-update
          token: ${{ secrets.GITHUB_TOKEN }}
          tap-token: ${{ secrets.GITHUB_TOKEN }}