on: push

jobs:

  build-and-upload:
    name: build and upload
    strategy:
      matrix:
        os: [macos, ubuntu]
# Disabling windows due to: https://github.com/oracle/graal/issues/4502
# Scheduled fix release: 22.2.0 (currently on 22.1.0)
#        os: [macos, ubuntu, windows]
        include:
          - os: ubuntu
            runs: ubuntu-latest
            artifact-name: sup-linux-amd64
          - os: macos
            runs: macos-latest
            artifact-name: sup-macos-amd64
#          - os: windows
#            runs: windows-2019
#            artifact-name: sup-windows-amd64.exe
    runs-on: ${{ matrix.runs }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: coursier/cache-action@v6

      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: build for windows
        if: matrix.os == 'windows'
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          ./sbt graalvm-native-image:packageBin

      - name: build for ${{ matrix.os }}
        if: matrix.os != 'windows'
        run: |
          ./sbt graalvm-native-image:packageBin

      # disable on window: https://github.com/upx/upx/issues/559
      - name: run upx on ${{ matrix.os }}
        if: matrix.os != 'windows'
        uses: svenstaro/upx-action@v2
        with:
          file: target/graalvm-native-image/scala-interactive-update
          args: --best --lzma

      - name: upload ${{ matrix.os }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact-name }}
          path: target/graalvm-native-image/scala-interactive-update

      - name: release binaries
        if: ${{ github.event.ref_type == 'tag' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/graalvm-native-image/scala-interactive-update
          asset_name: ${{ matrix.artifact-name }}
          overwrite: true
          tag: ${{ github.ref }}
